server:
  port: 8001
spring:
  application:
    name: discoveryServer
  profiles:
    #选择使用下面哪个配置项
    active: devProfile
   #服务配置信息
  cloud:
    config:
      #此处的config.profile会根据生效的active设置对应的值
      profile: ${config.profile}
      name: application
      uri: http://localhost:8888
      label: master
      discovery:
        service-id: configServer
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
#    data-center-info:
#    environment:
    status-page-url-path: /info
  server:
    # 设为false，关闭自我保护
    enable-self-preservation: false
    # 清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 10000


#info.build.name=@project.name@
#info.build.description=@project.description@
#info.build.groupId=@project.groupId@
#info.build.artifact=@project.artifactId@
#info.build.version=@project.version@
management:
  context-path: /admin
#将不同的配置组以---分割，并通过spring.profiles定义每组的名字，方便后续引用
---
spring:
  profiles: testProfile
config:
  profile: test

---
spring:
  profiles: devProfile
config:
  profile: dev

---
spring:
  profiles: prodProfile
config:
  profile: prod